### ISSUE TITLE
Feature of diesel example was incorrectly removed

### ISSUE THREAD

**Issue by Firstyear** [actix/examples#105]
In the update to 1.0.0 alpha, in the commit at : https://github.com/actix/examples/commit/f39a53ea3a3bdd8c7e783a9789c043f8aa4d4d71 an important example was removed. That was that you may have a route which will need to asynchronously communicate to an actor, as well as parsing and manipulating json.

Because this was removed to the trivial sql example, the value of the example as a complete application is diminished. Previously it showed how you would use async, and the correct types to allow a route handler to contact an actor, but now it loses that context and value.

I'd like the DbExecutor actor put back with the SyncArbiter, and the example updated to show how to communicate with actors asynchronously in 1.0.0. with json extractions.

Thanks,

**Comment by fafhrd91** [comment]
You can create new example with sync actors. I think new method is better, it requires less boilerplate code

**Comment by Firstyear** [comment]
Yeah, it might be less code, but there are people who may have more complex requirements or use cases, that want a more detailed example. Not every example should be trivial or minimalised.

I'm also not capable of making the example - I'm currently trying to make json extractors work with async and actors and I can't work out the type system and the errors, so I'm not exactly capable of providing the new example. I also find this frustrating because I created these examples for exactly these use cases, only to have them removed when they should have been updated.

So I'm asking you to help me please, by showing how this is done.

**Comment by fafhrd91** [comment]
SyncArbiter didn't change since 0.7 release.

**Comment by fafhrd91** [comment]
re-open if anyone wants to contribute

**Comment by slhmy** [comment]
😄 Hi, I found this issue when I'm trying to realize the example on https://actix.rs/docs/databases/. 

It is a little hard for me to work out the problem (I've learned rust for a month, and there are many things I need to learn).  
But I'm happy to say that I have just work out the example by myself, you can find a similar one in my repository https://github.com/slhmy/goods_management.  
It will be a pure CRUD, so it won't be hard to learn. 
So if someone need the example, it is a choice to refer to the above repository. 

I'm only a student now, so I'm not sure if my code is useful or not.  
It's really an exciting feeling to work out problems in rust. I mean I often runs into the problems like "when I need an example/documentation but there is not". But when I tried again and again and the program finally works, that is so wonderful! 👍
