### ISSUE TITLE
More Template Examples

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [actix/examples#122]
### Examples
According to [cargo's template engine category](https://crates.io/categories/template-engine) [handlebars](https://github.com/sunng87/handlebars-rust) is by far the most popular template engine and I think it would be super cool if you guys added an example for it

**Comment by fafhrd91** [comment]
Would you provide one?

**Comment by Th3Whit3Wolf** [comment]
I can try, I'm trying to familiarize myself with actix and combine it with another library to make a unnecessarily overbuilt [Startpage](https://github.com/Th3Whit3Wolf/Startpage) that more or uses html, css, and javascript but is written in all Rust so that
1.) My Rust oriented Startpage's repo code info is at least mostly Rust instead of  Javascript
2.) My Dotfiles Repo, which my Startpage is a subrepo of,  code info is also majority Rust instead of Javascript

But to address your question I will do my best to make one.
