### ISSUE TITLE
should be let counter = Arc::new(Mutex::new(0usize));

### ISSUE THREAD

**Issue by blackjune** [actix/examples#128]
https://github.com/actix/examples/blob/49fc6df22626a625f97652aaff6db8008f53f6a0/state/src/main.rs#L31

the result is 

> App data is not configured, to configure use App::data()

**Comment by krircc** [comment]
I think 0 is in usize, we no need write the Type everywhere.

**Comment by blackjune** [comment]
i think so, too

**Comment by krircc** [comment]
do you get some error or bug in the code ? 
can you list you error debug error info. it 's well when I try it.

**Comment by blackjune** [comment]
@krircc the error is
App data is not configured, to configure use App::data()

**Comment by fafhrd91** [comment]
@blackjune could you provide Pr?

**Comment by blackjune** [comment]
@fafhrd91 https://github.com/actix/examples/pull/129

**Comment by fafhrd91** [comment]
Thanks!
