### ISSUE TITLE
Using an async function with actix-web 1.0

### ISSUE THREAD

**Issue by milesgranger** [actix/examples#131]
I've been trying for some time now to use an `async` function with the latest (`1.0.0-rc`) of actix-web. Doesn't seem possible, and feel like I've exhausted all the different possibilities (via the futures preview [compatibility layer](https://rust-lang-nursery.github.io/futures-rs/blog/2019/04/18/compatibility-layer.html) ) and no luck so far. An example of doing this would be much appreciated! :+1:

**Comment by jesskfullwood** [comment]
I have made PR #132 you can use for inspiration, not sure if it can/should be merged while only working on nightly.

**Comment by milesgranger** [comment]
Great! I never explored the `.boxed_local` when trying to write my own wrapper, (and probably messed up in other places as well), thank you!

**Comment by fafhrd91** [comment]
https://github.com/saks/actix_web_async_compat

**Comment by rofrol** [comment]
Any news on that?

**Comment by fafhrd91** [comment]
async/await for 1.0 is out of scope. 2.0.0-alpha natively supports async/await

**Comment by rofrol** [comment]
So should I look here https://github.com/actix/actix-web/tree/v2.0.0-alpha.1 for any available examples using async/await?

**Comment by fafhrd91** [comment]
Yes

**Comment by JohnTitor** [comment]
actix-web is now 2.0.0 and most examples are using `async` functions, so closing.
