### ISSUE TITLE
How to return JSON response in simple-auth-server?

### ISSUE THREAD

**Issue by micfan** [actix/examples#137]
In this example, I replace this line by `r#"{}"#.into()`, this method return `"{}"` instead of `{}`,
how to turn it a JSON body instead of the quoted JSON?

https://github.com/actix/examples/blob/aa5750cafc9d6bc96e098c338b70fa618149ffd5/simple-auth-server/src/auth_handler.rs#L40

**Comment by fafhrd91** [comment]
Use .json() method

**Comment by micfan** [comment]
Solved, it seems the literal JSON string in `'static str` type, won't be parse and dump to a real JSON object, but a sub-type of String in JSON, in this line:

https://github.com/actix/examples/blob/aa5750cafc9d6bc96e098c338b70fa618149ffd5/simple-auth-server/src/errors.rs#L26
