### ISSUE TITLE
Unable to compile actix-redis

### ISSUE THREAD

**Issue by ganimp84** [actix/examples#156]
While trying to compile the example actix-redis, it couldn't resolve `SessionStatus`

error[E0432]: unresolved import `actix_session::SessionStatus`
 --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:4:30
  |
4 | use actix_session::{Session, SessionStatus};
  |                              ^^^^^^^^^^^^^ no `SessionStatus` in the root

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:148:21
    |
148 |                     (SessionStatus::Unchanged, None) =>
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:150:21
    |
150 |                     (SessionStatus::Unchanged, Some(state)) =>
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:162:21
    |
162 |                     (SessionStatus::Changed, Some(state)) =>
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:164:21
    |
164 |                     (SessionStatus::Purged, Some(_)) => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:181:21
    |
181 |                     (SessionStatus::Renewed, Some(state)) => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error[E0308]: mismatched types
   --> /Users/rustuser/.cargo/git/checkouts/actix-redis-0115bb10bc7e0d33/60f28d6/src/session.rs:194:21
    |
194 |                     (_, None) => unreachable!()
    |                     ^^^^^^^^^ expected enum `std::option::Option`, found tuple
    |
    = note: expected type `std::option::Option<impl std::iter::Iterator>`
               found type `(_, _)`

error: aborting due to 7 previous errors

Some errors occurred: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: Could not compile `actix-redis`.

Below is the Cargo.toml for your reference
```
[package]
name = "actix_redis"
version = "0.1.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.2"
actix-web = "1.0.0"
actix-redis = { git="https://github.com/actix/actix-redis.git" }
futures = "0.1.23"
redis-async = "0.4.0"
serde = "1.0.71"
serde_derive = "1.0.71"
env_logger = "0.6"
```

**Comment by fafhrd91** [comment]
should work now
