### ISSUE TITLE
Document how http-proxy and http-full-proxy are different

### ISSUE THREAD

**Issue by svenstaro** [actix/examples#164]
It's currently not clear where the "full" comes in. It should be documented in both READMEs.

**Comment by vmalloc** [comment]
I believe I'm the one who wrote it, and AFAIR there is a reference in the README I added... I'm guessing you mean add a note about the limitations of the non-full-one in its README?

**Comment by svenstaro** [comment]
So currently the full own says this:

    ## HTTP Full proxy example
    
    This proxy forwards all types of requests, including ones with body, to another HTTP server,
    returning the response to the client.
     
    To start:

And I don't really see this comparing itself to the non-full one. I think having two is fine if the difference is clearly communicated in both instances.

**Comment by vmalloc** [comment]
I wasn't sure why that functionality was omitted from the original example, and I didn't want to just modify it. Assuming nobody sees a point of keeping the old one I can open a PR to remove it...

**Comment by svenstaro** [comment]
I think the full one makes more sense. I'd opt to remove the other one.
