### ISSUE TITLE
Actix-web/juniper example context

### ISSUE THREAD

**Issue by lantos-lgtm** [actix/examples#178]
I was following the example at [actix-web/juniper](https://github.com/actix/examples/blob/master/juniper/src/main.rs)  but tried to implement context with out luck. Could someone update the example to include a simple context? 

I have tried to also follow from the juniper docs but it seems like context is implemented from the framework side.

```rs

struct Context {
}
impl juniper::Context for Context {};
stuct MyData {
  scema: Scema,
  context: Context
}

fn graphql(
    st: web::Data<Arc<MyData>>,
    data: web::Json<GraphQLRequest>,
) -> impl Future<Item = HttpResponse, Error = Error> {
    web::block(move || {
         //let res = data.execute(schema, &());
        let res = data.execute(&st.schema, &st.context); 
        // expecting &() rather then &st.context
        Ok::<_, serde_json::error::Error>(serde_json::to_string(&res)?)
    })
    .map_err(Error::from)
    .and_then(|user| {
        Ok(HttpResponse::Ok()
            .content_type("application/json")
            .body(user))
    })
}
```

I saw @fafhrd91 added the example blob are you able to help?

**Comment by clifinger** [comment]
I did a complete example in my repo : https://github.com/clifinger/canduma

**Comment by LantosTG** [comment]
I did something similar @clifinger, 
https://github.com/LantosTG/rust_site

I omitted diesel. I found it to be more restrictive then helpful as if I was writing the sql to create the tables I figured it would be easier to map query results and de-erialize them. For an orm I think that the rust structs should be the source of truth.

How did you find implementing diesel in your repo?

Also this would be great to subscriptions implemented when actix-web/juniper permit it.

Nice work @clifinger !

edit: I realize the project was private, I was wondering why no one commented on it

**Comment by LantosTG** [comment]
Speak of the devil
https://github.com/graphql-rust/juniper/pull/433/files/54d4becf87d76b6bd47268e824234265d7c5d249..90873acb1bd7ec1245bff869521614261c0cff18

**Comment by clifinger** [comment]
> I did something similar @clifinger,
> https://github.com/LantosTG/rust_site
> 
> I omitted diesel. I found it to be more restrictive then helpful as if I was writing the sql to create the tables I figured it would be easier to map query results and de-erialize them. For an orm I think that the rust structs should be the source of truth.
> 
> How did you find implementing diesel in your repo?
> 
> Also this would be great to subscriptions implemented when actix-web/juniper permit it.
> 
> Nice work @clifinger !
> 
> edit: I realize the project was private, I was wondering why no one commented on it

Hello @LantosTG , Nice work also !

To be honnest, I will work with sql directly for my own project.
But as a boilerplate, I prefer to give an example with Diesel (popularity).

I did some changes today about JWT (no more authentication with it), I let you check an read why in the security chapter of the readme :)

**Comment by robjtede** [comment]
https://github.com/actix/examples/tree/master/graphql/juniper-advanced has context
