### ISSUE TITLE
diesel example doesn't seem to work?

### ISSUE THREAD

**Issue by stevendesu** [actix/examples#187]
I just cloned `actix/examples`, installed diesel via `cargo install diesel_cli`, left the default `DATABASE_URL` (`test.db`, using SQLite), then ran `cargo run`

The web server started and I opened it up in a browser: http://localhost:8080/test

This opened a blank page, but I saw an access log in the console were `cargo run` was running

I then killed the program (CTRL+C) and checked out the database by running `sqlite3 test.db`, `select * from users;` -- and there was nothing in the table

I'm pretty new to Rust and ***extremely*** new to Actix and Diesel. Was kind of hoping it would just work to prove to me that it's easy to get up and running.

**Comment by tobx** [comment]
I have the same issue. I guess the readme needs to be updated.
