### ISSUE TITLE
Diesel Example Not Working with Actix 0.6.0

### ISSUE THREAD

**Issue by incubus8** [actix/examples#20]
Hi,

It seems that the example is not working with Actix 0.6.0

The problematic code:
https://github.com/actix/examples/blob/master/diesel/src/main.rs#L38

```rust
/// State with DbExecutor address
struct AppState {
    db: Addr<Syn, DbExecutor>,
}
```

Any idea how to make it work? I am newbie to Rust.

**Comment by fafhrd91** [comment]
Use 0.5 version. Actix 0.6 works with actix-web 0.7

**Comment by incubus8** [comment]
@fafhrd91 since the API spec is changed for `Addr`, an updated example (that follows https://github.com/actix/actix/blob/master/MIGRATION.md) will be appreciated.

**Comment by fafhrd91** [comment]
let's wait. all examples work with released version of actix-web. and it is 0.6.13.

or we can make a branch for actix-web master
