### ISSUE TITLE
Login Example

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [actix/examples#203]
It would be nice to have an example of how do to something [similar to forward guards in Rocket](https://rocket.rs/v0.4/guide/requests/#forwarding-guards)

I've been going through the examples and documentation and have been unable to find something similar. I know people here are probably busy with actix 2.0.0 but if you could give me some help I might be able to make a pull request with an example.

**Comment by vmalloc** [comment]
You're probably looking for something like an "identity" extractor to use in your routes. The trick is to define it in your code, something like:
```rust
pub(crate) struct Identity {
...
}
```
Inside it will be the credentials/identification information. Then implement a `FromRequest` for it:
```rust
impl actix_web::FromRequest for Identity {
    type Error = Error;
    type Future = Result<Self, Self::Error>;
    type Config = ();

 
    fn from_request(req: &HttpRequest, payload: &mut actix_web::dev::Payload) -> Self::Future {
        ...
   }
}
```
In case you need to access an additional application data like the database connection, you can do so by:
```rust
        let db = web::Data::<DB>::from_request(req, payload).unwrap();
```
Hope this helps

**Comment by Th3Whit3Wolf** [comment]
Is this what's happening [here in cookie-auth](https://github.com/actix/examples/blob/master/cookie-auth/src/main.rs)?

**Comment by vmalloc** [comment]
Very similar in the bare concept, but actix-identity is pretty new and it seems from a quick glance it's only for actix-web 2.0.0 -- my example shows how to go about writing your own identity service, and to show it's not too complicated. 

In my project I ended up writing my own because I needed to support multiple weird authentication mechanisms.

**Comment by Th3Whit3Wolf** [comment]
Oh okay. Thank you!
