### ISSUE TITLE
Oauth 2 Example

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [actix/examples#208]
I found this [actix web oauth 2](https://github.com/pka/actix-web-oauth2) and I thought it belonged here.

**Comment by cdbattags** [comment]
feel free to open a PR?

**Comment by Th3Whit3Wolf** [comment]
I posted an issue in the author's repo asking if he would submit a pr.

**Comment by realaravinth** [comment]
Please refer to the examples from [oxide-auth](https://github.com/HeroicKatora/oxide-auth/tree/master/oxide-auth-actix/examples/actix-example) Oauth crate. They have an actix-web specific example too!
