### ISSUE TITLE
I think the README.md in websocket-tcp-chat needs to be updated

### ISSUE THREAD

**Issue by 3442853561** [actix/examples#226]
https://github.com/actix/examples/blob/master/websocket-tcp-chat/README.md  
https://github.com/actix/examples/blob/master/websocket-chat/README.md  

They look like most of the text is exactly the same, which is not friendly for beginners.

https://github.com/actix/actix/tree/master/examples/chat

Especially after reading this code, if you want to know what the next step is, you must read the code in the above two projects carefully.

There are some suggestions:

Explain their differences and even point to this issue. Or merge their code, if their differences are pointed out it is not necessary.

**Comment by JohnTitor** [comment]
It'd be nice that websocket-tcp-chat explains the difference from websocket-chat.
