### ISSUE TITLE
form data example

### ISSUE THREAD

**Issue by fafhrd91** [actix/examples#24]

**Comment by casperin** [comment]
Yes please! I've been at this for 2 days now.

https://stackoverflow.com/questions/51156656/how-do-i-get-the-parameters-from-a-post-request-from-a-html-form-in-actix-web

**Comment by casperin** [comment]
I just realized that you are the person who responded on that SO question. Thanks for pointing me in the right direction; I wish it was enough for me to get it, so I could create the example myself and do a PR on it. ... Rust is difficult. It really is.

**Comment by DoumanAsh** [comment]
@casperin I added a bit more detailed [answer](https://stackoverflow.com/a/51169326) with step by step instruction how to handle form data

**Comment by casperin** [comment]
Thank you so much. I'll get on it again. One thing that still isn't immediately clear from your example is how to access the request in the handler. But let me first see if I can get what you wrote to compile in the first place.

Just to be clear, the example you are referring to is [this one](https://actix.rs/actix-web/actix_web/struct.Form.html#example), right?

**Comment by DoumanAsh** [comment]
@casperin Yes that one, the thing is that after using extractors you don't have access to original request. The point of extractors though is to transform your request into more suitable data, but for what reason would you need request itsef

**Comment by casperin** [comment]
I jumped into Gitter, but in interest of others dropping by from a google search: To save the logged in state. Something like

```rust
    if params.password == "abc123" {
        req.remember("logged-in".to_owned());
        // redirect to home
    };
```
