### ISSUE TITLE
example of combination: actix & actix-web

### ISSUE THREAD

**Issue by GopherJ** [actix/examples#257]
Hello, actix is not supported out of box since actix-web@1.0, can we get an example of the correct way of using it in 1.0 & 2.0?

Thanks

**Comment by robjtede** [comment]
To an extent, the websocket* examples show integration of the two. Take a look and tell us if there's something you think we add.

**Comment by GopherJ** [comment]
Thanks @robjtede I think that solved already my problems. Sorry haven't noticed that.
