### ISSUE TITLE
http-proxy Segmentation fault when SIGINT on macOS

### ISSUE THREAD

**Issue by fbucek** [actix/examples#261]
Seg. fault when closing `http-proxy` on `macOS` ( on ubuntu 18.04 it is working fine - no seg. fault )

Crashes with `Segmentation fault 11`

Step to reproduce on `macOS 10.15.3` `cargo 1.41.0 (626f0f40e 2019-12-03)`

1. run http-proxy `cargo run localhost 8080 google.com 80`
2. `ctrl+c` or `pkill http-proxy` -> `Segmentation fault: 11`

```bash
git clone https://github.com/actix/examples.git
cd examples/http-proxy
cargo run localhost 8080 google.com 80
```

**Comment by robjtede** [comment]
closing as stale; cant reproduce
