### ISSUE TITLE
example-diesel thread block

### ISSUE THREAD

**Issue by Icatream** [actix/examples#266]
<https://github.com/actix/examples/blob/master/diesel/src/main.rs#L27>
I suppose `pool.get()` would block the current thread.
It should be something like this.
```
let pool = pool.clone();
// use web::block to offload blocking Diesel code without blocking server thread
let user = web::block(move || {
  let conn = pool.get().expect("couldn't get db connection from pool");
  actions::find_user_by_uid(user_uid, &conn)
})
```
I'm not sure if the `pool` need to be `clone`.

**Comment by JohnTitor** [comment]
@Icatream Seems reasonable to me, feel free to submit a PR!

**Comment by robjtede** [comment]
pool acquires are in web::block now
