### ISSUE TITLE
Pin<Box<_>> in async_db

### ISSUE THREAD

**Issue by cerven** [actix/examples#282]
In example async_db there is fn `parallel_weather `, where are futures wrapped into Box::pin and then passed into `join_all`. I tried remove these Box::pin and let there just plain futures and it works well too. I think `join_all` makes this "wrapping" internally and it is not requiered do it there.
In my opinion, futures in this code are then "pin-boxed" 2x, am I right?

**Comment by robjtede** [comment]
You could be right, I think it's may matter more when the db lookups dont all return the same type.
