### ISSUE TITLE
An example for serverless usage

### ISSUE THREAD

**Issue by Cokemonkey11** [actix/examples#29]
Hi, is it presently possible to use actix-web for serverless?

In other words: the application is invoked to render a single endpoint before terminating.

So, rather than the usual

```
fn main() {
    let body = server::new(
        || App::new()
            .route("/{id}/{name}/index.html", http::Method::GET, index))
        .bind("127.0.0.1:8080").unwrap()
        .run();
}
```

I'm looking for something like

```
fn main() {
    let args = std::env::args().into_iter();
    let method: http::Method = args.next().unwrap_or("GET").parse();
    let path = args.next().unwrap_or("/");

    let body = server::new(
        || App::new()
            .route("/{id}/{name}/index.html", http::Method::GET, index))
        .invoke(method, path)
        .expect("Failed to render path.");

    println!("{}", Responder::new(body));
}
```

**Comment by Cokemonkey11** [comment]
Thanks - are there any published examples of using TestServer?

The one in docs looks like a good start. I will find out soon if there's anything I'd want in an MWE that's missing...

**Comment by Cokemonkey11** [comment]
Looks like there is only a capability to handle `/` route - is that right?

https://actix.rs/actix-web/src/actix_web/test.rs.html#335-341

I need to run this fire-once server with arbitrary routes, starting up with multiple handlers.

(As above, this is for running in a serverless platform)

**Comment by Cokemonkey11** [comment]
Thanks for the link. For a serverless example, it seems imperfect but useful.

I can't seem to compile a cut and pasted example though:

```
error[E0599]: no method named `responder` found for type `futures::AndThen<tokio_timer::Delay, std::result::Result<std::string::String, tokio_timer::Error>, [closure@src/main.rs:50:35: 52:26 p:_, data:_]>` in the current scope
  --> src/main.rs:53:26
   |
53 |                         .responder()
   |                          ^^^^^^^^^
   |
   = note: the method `responder` exists but the following trait bounds were not satisfied:
           `futures::AndThen<tokio_timer::Delay, std::result::Result<std::string::String, tokio_timer::Error>, [closure@src/main.rs:50:35: 52:26 p:_, data:_]> : actix_web::AsyncResponder<_, _>`
           `&futures::AndThen<tokio_timer::Delay, std::result::Result<std::string::String, tokio_timer::Error>, [closure@src/main.rs:50:35: 52:26 p:_, data:_]> : actix_web::AsyncResponder<_, _>`
           `&mut futures::AndThen<tokio_timer::Delay, std::result::Result<std::string::String, tokio_timer::Error>, [closure@src/main.rs:50:35: 52:26 p:_, data:_]> : actix_web::AsyncResponder<_, _>`
```

What do you think?

**Comment by DoumanAsh** [comment]
@Cokemonkey11 If you look at [Responder](https://actix.rs/actix-web/actix_web/trait.Responder.html) you see that it requires your future to be convertible to HttpResponse and actix-web error

`tokio_timer::Delay` is definitely couldn't be converted to HTTP Response.
What compiler here is trying to say is that the future cannot implement `AsyncResponder` trait due to it not meeting requirements.

**Comment by fafhrd91** [comment]
it is possible with 1.0
