### ISSUE TITLE
There are two graphQl example. both using Juniper. Should one be removed?

### ISSUE THREAD

**Issue by kunjee17** [actix/examples#295]
Hi, First of all. Thanks for all examples. As some cleaning up of repo is going on (figure out from commit messages). It would be great if graphQL example can be merged. As of now there are two examples in repo and both are using Juniper. I haven't look into details but if there is no significant difference then once should be and can be removed.

**Comment by JohnTitor** [comment]
So, the `graphql-demo` example has more detail than the `juniper` example, we could remove the later.
But if someone wants to have simple example, we could just rename them to clarify (I guess `graphql-demo` should be `juniper-r2d2` or something else).

**Comment by kunjee17** [comment]
@JohnTitor  that would be great. Because I m new to actix and rust. So, at least I know where to start and where I can find advanced example.
