### ISSUE TITLE
Request: example with SQLx

### ISSUE THREAD

**Issue by zmilan** [actix/examples#296]
Does anyone use [SQLx](https://github.com/launchbadge/sqlx/) with Actix-web? Is it possible to create some extremely simple examples like todo or something?

**Comment by JohnTitor** [comment]
Feel free to submit a PR <3

**Comment by zmilan** [comment]
@JohnTitor I have struggled with it yesterday morning, but later that day I have made it works. I will submit PR today or over the weekend, as soon as I get a chance to clean it little and play little more with it.

**Comment by zmilan** [comment]
@JohnTitor I have submitted PR with example todo api
