### ISSUE TITLE
Actix websocket examples - How to make non-blocking / async?

### ISSUE THREAD

**Issue by dessalines** [actix/examples#297]
I have a websocket app ([Lemmy](https://github.com/lemmynet/lemmy)) , and its primarily using Actix's [websocket-tcp-chat](https://github.com/actix/examples/blob/master/websocket-tcp-chat/) as a basis. 

However I'm finding that every action done, by the single `ChatServer` actor, is blocking, whether its doing DB calls, http fetches, or anything. I've tried using `SyncArbiter` and `SyncContext`, but then my shared state gets lost. 

Is there any working example of async actions with websockets? IE, how do I use `web::block` with websockets?

**Comment by robjtede** [comment]
did you get anywhere with this @dessalines ?

**Comment by dessalines** [comment]
I'm not sure if this is the correct way, or even really if its working, but in the `handle` function for the websocket actor:

```
  fn handle(&mut self, msg: StandardMessage, ctx: &mut Context<Self>) -> Self::Result {
    let fut = self.do_fut_stuff(msg, ctx); // do web::block inside here
    Box::pin(async move {
      match fut.await {
        Ok(m) => {
          info!("Message Sent: {}", m);
          Ok(m)
        }
        Err(e) => {
          error!("Error during message handling {}", e);
          Ok(e.to_string())
        }
      }
    })
  }
```

And in the `websocket.rs`, I'm using `.spawn()` instead of `.wait()` like in the example. Again, I have no idea if this is the correct way to do it.

**Comment by robjtede** [comment]
@Jonathas-Conceicao should be easy enough to migrate the examples to using async methods right?

**Comment by robjtede** [comment]
closing as stale
