### ISSUE TITLE
OpenSSL example certificate is expired

### ISSUE THREAD

**Issue by superlou** [actix/examples#312]
The certificate in the [openssl example](https://github.com/actix/examples/tree/master/openssl) looks like it expired in March. The example works otherwise. What would be the `openssl` command line used to generate a new certificate?

**Comment by Firstyear** [comment]
A better idea could be to generate an ephemeral certificate instead in memory? I have an example of that here with actix:

https://github.com/Firstyear/webauthn-rs/blob/master/examples/actix/crypto.rs

**Comment by superlou** [comment]
That is an interesting idea from a maintainability perspective, though I was asking somewhat selfishly, as when I try to integrate that example into my app I get SSL_ERROR_RX_RECORD_TOO_LONG in the browser. I was hoping that my self-generated certificate was the problem.
