### ISSUE TITLE
[error] cargo run --bin websocket-chat-server

### ISSUE THREAD

**Issue by tingleiwuyan** [actix/examples#314]
cargo run --bin websocket-chat-server

error: could not compile `http`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name http /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/http-0.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=fe38d6954dae0369 -C extra-filename=-fe38d6954dae0369 --out-dir /home/ubuntu/examples/target/debug/deps -L dependency=/home/ubuntu/examples/target/debug/deps --extern bytes=/home/ubuntu/examples/target/debug/deps/libbytes-f237e4fdbde55cdd.rmeta --extern fnv=/home/ubuntu/examples/target/debug/deps/libfnv-bb61b7b54d25c2fd.rmeta --extern itoa=/home/ubuntu/examples/target/debug/deps/libitoa-33191e70f23cc964.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)

**Comment by JohnTitor** [comment]
> error: could not compile http.

I believe it isn't actix-related problem but your local one. Also, the code work fine on CI and my local so I'm going to close this issue.
