### ISSUE TITLE
Adding SSE examples using HttpContext and Channel

### ISSUE THREAD

**Issue by fafhrd91** [actix/examples#32]

**Comment by greenteamsite** [comment]
It would be very useful for me

**Comment by Songtronix** [comment]
Does 1.0 still have HttpContext? Can't find it.

**Comment by arve0** [comment]
I made [this example](https://github.com/arve0/actix-sse/blob/master/src/main.rs), which uses a [mutex lock](https://doc.rust-lang.org/std/sync/struct.Mutex.html) along with a [tokio bytes channel](https://docs.rs/tokio/0.1.22/tokio/sync/mpsc/fn.channel.html?search=). Not sure how it scales, will `Sender::try_send` block? 

Also, what would be a better way to detect stale clients? Implement an actor in `new_client` (the event source handler), which keeps track the connection state?

**Comment by stellanhaglund** [comment]
Is that the best way to detect client disconnects, couldn't it be handle by detecting the tcp disonnect?
