### ISSUE TITLE
What's the meaning of "diesel=debug" in the log level?

### ISSUE THREAD

**Issue by foisonocean** [actix/examples#322]
https://github.com/actix/examples/blob/bc6f614f78/diesel/src/main.rs#L67

As far as I know, diesel doesn't have a log system ([link](https://github.com/diesel-rs/diesel/issues/150)), so why "diesel=debug" is here, does it really work? Or am I missed something?

**Comment by robjtede** [comment]
true enough, diesel doesn't depend on `log` so this won't do anything

**Comment by foisonocean** [comment]
@robjtede 
So can we remove "diesel=debug"? This will make people confused.

**Comment by robjtede** [comment]
sure, PR welcome
