### ISSUE TITLE
websocket example does not work

### ISSUE THREAD

**Issue by NikosEfthias** [actix/examples#325]
`cargo run --bin websocket-server` fires the server up on port 8080
on firefox `new WebSocket("ws://127.0.0.1:8080")` says `Firefox can’t establish a connection to the server at ws://127.0.0.1:8080/` however I see the log `actix_web::middleware::logger] 127.0.0.1:58886 "GET / HTTP/1.1" 200 2394 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" 0.000666` on the console 

I also tried using websocat the response is 
```
websocat: WebSocketError: Received unexpected status code
websocat: error running
```

**Comment by rustrust** [comment]
Relevant to https://github.com/actix/actix-web/issues/1006

**Comment by mlodato517** [comment]
Is it because the resource is [`/ws/`](https://github.com/actix/examples/blob/master/websocket/src/main.rs#L107)? I think I see it work if I use:
```js
const ws = new WebSocket("ws://127.0.0.1:8080/ws/")
// wait a second to connect
ws.readyState === ws.OPEN
```
