### ISSUE TITLE
Why is blocking used in this example?

### ISSUE THREAD

**Issue by Alfriadox** [actix/examples#337]
https://github.com/actix/examples/blob/399fbee1e4db49d8c51fb70ed0916d0743b26c04/diesel/src/main.rs#L55

**Comment by Alfriadox** [comment]
It doesn't make sense to me; since this function is async, and `.await` is immediately called on the result of the call to `web::block`, wouldn't it make more sense to just call `actions::insert_new_user` without using a new threadpool through `web::block`? The comment indicates that without it, it would block the main thread, but it's called in a service isn't it already off the main thread?

**Comment by fMeow** [comment]
Actix web uses tokio and coroutine instead of thread for concurrency. In tokio, all Future are spawned in a single thread and managed via executor. If you call a blocking function, it can halt the executor loop.

**Comment by fakeshadow** [comment]
`web::block` uses a future aware oneshot channel to bridge the the sync threadpool and actix runtime. When you call await on `web::block` you are waiting on the receiver of said channel and it's not blocking. Your "main thread" would be able to switch to other async task and handle them until the receiver get result ready and waked up. 
If you call the sync code directly you would block the actix runtime until it's done.

**Comment by Alfriadox** [comment]
this could be better documented I think
