### ISSUE TITLE
ToDo example: cannot build

### ISSUE THREAD

**Issue by jepster** [actix/examples#339]
If I try to build the ToDo example, I am getting the following error:

>  = note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"libpq.lib\" kann nicht ge\xf6ffnet werden.\r\n

I have executed "cargo build" in the todo folder. I am using Windows 10 Pro 64 Bit with Rust.

**Comment by JohnTitor** [comment]
The examples uses the diesel crate with postgres feature and README mentions their prerequisites. Make sure you've installed postgres. Closing as wontfix.
