### ISSUE TITLE
build is broken (no AlpnError in ssl)

### ISSUE THREAD

**Issue by MarkSwanson** [actix/examples#34]
error[E0432]: unresolved import `openssl::ssl::AlpnError`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.3/src/server/srv.rs:23:20
   |
23 | use openssl::ssl::{AlpnError, SslAcceptorBuilder};
   |                    ^^^^^^^^^ no `AlpnError` in `ssl`

**Comment by fafhrd91** [comment]
i think you need openssl 1.0.1

**Comment by MarkSwanson** [comment]
Oh hey, I was compiling on an old Ubuntu 14 machine that I've been too lazy to upgrade.
I switched to an Ubuntu 16 box and it compiled fine.
Thanks!

**Comment by fafhrd91** [comment]
you can use rust-tls feature on Ubuntu 14
