### ISSUE TITLE
replace std::time::sleep with an async sleep in async_db example

### ISSUE THREAD

**Issue by Dowwie** [actix/examples#350]
incorrect implementation as the current solution sleeps the entire thread: https://github.com/actix/examples/blob/a3faea082b9d946a4c76792bdeecefd047f9ccf4/async_db/src/db.rs#L32

instead, the example should use async sleep from either tokio or async-std

reference: https://blog.hwc.io/posts/rust-futures-threadsleep-and-blocking-calls-inside-async-fn/

**Comment by fakeshadow** [comment]
Well what runs inside `web::block` is pure synchronous so I don't think any async timer functions can be runned. Unless you construct an executor in it and call block_on on it which would result in the same blocking result.

I believe the sleep is to simulate long time blocking functions like heavy compuation or heavy sync db query. The duration is a bit aggressive I agree that it drains all threads very quickly.

**Comment by Dowwie** [comment]
Yea, I wrote this example back in the day.  To be honest, the async timer
issue hit me during other work so I filed the issue before I forgot without
even looking at the execution context.  Good catch.
