### ISSUE TITLE
Suggestion: example from community

### ISSUE THREAD

**Issue by carrascomj** [actix/examples#351]
Hi!

I propose a repository of mine as an example from the community: https://github.com/carrascomj/dalted

It provides an example of integration with image-rs for a web-app, with this features:
* Simple workflow to [accept an image from a POST request](https://github.com/carrascomj/dalted/blob/master/src/routes/post.rs#L15), [transform](https://github.com/carrascomj/dalted/blob/master/src/image_processing/pipe_transform.rs#L32) the image and return the transformed results to the front-end (with a bit of [serde](https://serde.rs/) in the process).
* Minimal Front-end with HTML5 (it doesn't use any web-framework). It solely uses [Tera](https://github.com/Keats/tera) for handling 404 Errors.
* Live example, the final result can be seen at https://dalted.tech

I hope it is useful.

**Comment by JohnTitor** [comment]
@carrascomj Feel free to send a PR!
