### ISSUE TITLE
example that demonstrates running background tasks alongside the web server

### ISSUE THREAD

**Issue by ivkovici** [actix/examples#361]

**Comment by OutOfBoundCats** [comment]
does it refer to running actix server on different thread and then starting something else in loop on different thread and then awaiting both in main thread?

**Comment by robjtede** [comment]
the modern approach would probably be more like a separate task rather than thread but i would consider either

**Comment by robjtede** [comment]
https://github.com/actix/examples/tree/master/background-jobs
