### ISSUE TITLE
How could I change http-proxy's payload limit size?

### ISSUE THREAD

**Issue by kazuhei2** [actix/examples#362]
I am using http-proxy codes and meet an error message "A payload reached size limit.". I sent a request to proxy and got a log like followings.

```rust
async fn forward(
    req: HttpRequest,
    body: web::Bytes,
    url: web::Data<Url>,
    client: web::Data<Client>,
) -> Result<HttpResponse, Error> {
    let mut new_url = url.get_ref().clone();
    new_url.set_path(req.uri().path());
    new_url.set_query(req.uri().query());

    // TODO: This forwarded implementation is incomplete as it only handles the inofficial
    // X-Forwarded-For header but not the official Forwarded one.
    let forwarded_req = client
        .request_from(new_url.as_str(), req.head())
        .no_decompress();
    let forwarded_req = if let Some(addr) = req.head().peer_addr {
        forwarded_req.header("x-forwarded-for", format!("{}", addr.ip()))
    } else {
        forwarded_req
    };

    debug!("forwarded_req: {:?}", forwarded_req);
    let mut res = forwarded_req.send_body(body).await.map_err(Error::from)?;
    debug!("res: {:?}", res);

    let mut client_resp = HttpResponse::build(res.status());
    debug!("client_resp: {:?}", client_resp);
    // Remove `Connection` as per
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection#Directives
    for (header_name, header_value) in
        res.headers().iter().filter(|(h, _)| *h != "connection")
    {
        client_resp.header(header_name.clone(), header_value.clone());
    }

    Ok(client_resp.body(res.body().await?))
}
```

[2020-09-10T02:15:45Z INFO  actix_web::middleware::logger] 192.168.1.225:45104 "GET /js/app.js HTTP/1.1" 413 29 "-" "curl/7.58.0" 0.013406
[2020-09-10T02:31:15Z DEBUG gen_http_proxy] forwarded_req: 
    ClientRequest HTTP/1.1 GET:http://192.168.1.87/js/app.js
      headers:
        "accept": "*/*"
        "x-forwarded-for": "192.168.1.225"
        "host": "192.168.1.225:8080"
        "user-agent": "curl/7.58.0"
    
[2020-09-10T02:31:15Z DEBUG gen_http_proxy] res: 
    ClientResponse HTTP/1.1 413 Payload Too Large
      headers:
        "date": "Fri, 04 Sep 2020 02:35:32 GMT"
        "content-type": "text/plain; charset=utf-8"
        "content-length": "29"
    
[2020-09-10T02:31:15Z DEBUG gen_http_proxy] client_resp: 
    ResponseBuilder HTTP/1.1 413 Payload Too Large
      headers:

A response size is expected about 800KB, but http-proxy couldn't receive a large payload. How could I change the limit of payload size?

**Comment by Neopallium** [comment]
You can add a `PayloadConfig`/`JsonConfig`/`FormConfig` as an `app_data()` to control the request payload limit.

For the `http_proxy` example use a `PayloadConfig`:
```rust
HttpServer::new(move || {
        App::new()
            .app_data(web::PayloadConfig().limit(1024 * 1024)) // set payload limit to 1Mbyte.
            .data(Client::new())
            .data(forward_url.clone())
            .wrap(middleware::Logger::default())
            .default_service(web::route().to(forward))
    })
```

**Comment by kazuhei2** [comment]
Thank you. I tried PayloadConfig like followings, but I got the same error.

```rust
      HttpServer::new(move || {
          App::new()
              .app_data(web::PayloadConfig::new(1024 * 1024))
              .data(Client::new())
              .data(forward_url.clone())
              .wrap(middleware::Logger::default())
              .default_service(web::route().to(forward))
      })
```

**Comment by kazuhei2** [comment]
The real problem was a small size of limit of HttpResponse body. In forward function in main.rs of http-proxy at end line, I added .limit(1024 * 1024) and http-proxy works.

```rust
    Ok(client_resp.body(res.body().limit(1024 * 1024).await?))
```

**Comment by Neopallium** [comment]
I will take a look at improving that example later.
