### ISSUE TITLE
Juniper example not working

### ISSUE THREAD

**Issue by felix-d** [actix/examples#38]
Hi! I'm trying to run the juniper example, but the schema does not seem to be loaded properly in graphiql and I get 404s when trying to run a query.

<img width="986" alt="screen shot 2018-08-17 at 4 56 37 pm" src="https://user-images.githubusercontent.com/5751476/44288503-88b47500-a23e-11e8-9641-344093e19890.png">

I'm not familiar with Juniper nor Actix so it would take me a while to debug. Any idea what's broken? Thank you!

**Comment by felix-d** [comment]
Oh yeah 🤦‍♂️ I didn't look at the console, only the network tab. I would have seen this right away. Simply accessing `127.0.0.1` instead of `localhost` makes it work. However, if I want to use `localhost`, your solution does not seem to work, I still hit the CORS issue.

**Comment by felix-d** [comment]
FYI this seems to work

```rust
    server::new(move || {
        App::with_state(AppState{executor: addr.clone()})
            .middleware(middleware::Logger::default())
            .configure(|app| {
                 middleware::cors::Cors::for_app(app)
                    .allowed_origin("http://localhost:8383")
                    .resource("/graphql", |r| r.method(http::Method::POST).with(graphql))
                    .register()
            })
           .resource("/graphiql", |r| r.method(http::Method::GET).h(graphiql))
    }).bind("127.0.0.1:8383")
        .unwrap()
        .start();
```

**Comment by Jayuda** [comment]
Hello @felix,
i am still error : 
```
 actix_web::pipeline: Error occurred during request handling: Origin is not allowed to make this request
 actix_web::middleware::logger: 127.0.0.1:50272 "POST /graphql HTTP/1.1" 400 42 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) GraphQLPlayground/1.8.4 Chrome/61.0.3163.100 Electron/2.0.11 Safari/537.36" 0.000199
```

are you have clue about it ? Thanks
