### ISSUE TITLE
How to upload form data and files in the same form / Err(Boundary) on file upload

### ISSUE THREAD

**Issue by fschutt** [actix/examples#382]
I have a form that essentially looks like this:

```rust
// not real code
pub struct UploadOrderForm {
    order_id: usize,                        // input type = text
    pdf_file: File,                         // input type = file
    ai_file: File,                          // input type = file
    csv_file: Option<File>,                 // input type = file, optional
    checked_for_errors: Option<String>,     // input type = checkbox
}
```

I've looked at the multipart example, but it gives me an `Err(Boundary)` if I implement it like this:

```rust
// not real code
pub struct UploadOrderForm {
    order_id: usize,                        // input type = text
    checked_for_errors: Option<String>,     // input type = checkbox
}

pub async fn upload_order(
    form: Form<UploadOrderForm>, 
    payload: Multipart, 
    data: Data<ApplicationData>, 
    session: Session, 
    req: HttpRequest
) -> impl Responder {

    println!("form: {:?}", form); // works fine

    match payload.try_next().await { // returns Err(Boundary) - "Multipart boundary is not found" - what does that mean?
        Ok(Some(mut field)) => {
            let content_type = field.content_disposition().unwrap();
            let filename = content_type.get_filename().unwrap();

            println!("content_type: {}", content_type);
            println!("file name: {}", filename);

            let mut file_data = Vec::<u8>::new();

            while let Some(chunk) = field.next().await {
                let data = chunk.unwrap();
                file_data.extend_from_slice(&data);
            }

            println!("file data: {} bytes", file_data.len());
        },
        o => {
            println!("error: {:?}", o);
        }
    }
}
```

The form is parsed correctly, but I can't access my files, it just returns an `Err(Boundary)`.

Is there a way that I can get the files by their original names, i.e. if I have an `<input type="file" name="pdf_file" />`, can I somehow distinguish which file stream came from the `pdf_file` field and which file came from the `ai_file` field?

Also, if I reverse the order of the `Multipart` and `Form<UploadFormData>` in the signature, I get a `Parse error`. Maybe it should be mentioned in the documentation that the `Multipart` has to come after the form data.

**Comment by fakeshadow** [comment]
It has nothing to do with order. Form and Multipart both are types that would consume your response body. You can't eat the cake and have it. Extracting multiple types that would take the payload is not yet supported. That said even if it's supported you probably would want to aviod using it as copying a response body for upload could be costly.

**Comment by fschutt** [comment]
> Extracting multiple types that would take the payload is not yet supported.

Could it be supported (to support a use case like this)?

In the meantime, I probably have to fall back to javascript, i.e. construct one ajax request for the form data and one request for the files and hope it works out.

> That said even if it's supported you probably would want to aviod using it as copying a request body for upload could be costly.

Well it's a company-internal form to upload a finished order, performance literally doesn't matter.

**Comment by fakeshadow** [comment]
There is an issue about this https://github.com/actix/actix-web/issues/1724.
Nothing landed yet.

**Comment by fschutt** [comment]
If anyone still has this error (I ran into it again and found my own issue on Google): 

**You have to add `enctype="multipart/form-data` to the `<form />`, otherwise it's not going to work with actix!**

**Comment by GreenTeaSeb** [comment]
Is this supported now? Been trying to set it up, but to no avail.
