### ISSUE TITLE
How to send a in memory CSV as a response

### ISSUE THREAD

**Issue by asnimansari** [actix/examples#385]
HI,
I have generated a CSV using `csv="1.1"`. I have it in memory. How do I send it as a response?
Once a person opens the URL, it should start downloading this file

**Comment by vmalloc** [comment]
You can just send it as a string (as `impl Responder` or as an `HttpResponse::Ok().body(csv)`.

About the download part, you probably want to set a custom content-disposition header to make the browser download the file instead of display it.
