### ISSUE TITLE
NATS messages + Actix websockets

### ISSUE THREAD

**Issue by pashinin** [actix/examples#394]
I want to listen to [NATS](https://nats.io/) ([docs](https://docs.rs/nats/0.8.6/nats/)) messages and send data to user over websocket.

I can do something like this (subscribe to NATS messages on "started" event):

```
impl Actor for MyWs {
    type Context = ws::WebsocketContext<Self>;

    fn started(&mut self, ctx: &mut ws::WebsocketContext<Self>) {
        self.nats.subscribe(&format!("{}", self.uuid)).unwrap().with_handler(|msg| {
            println!("Received {}", &msg);
            // ctx.text("text");
            Ok(())
        });

   ...
```

And it is working but I can't use `ctx` inside closure to send data over websocket. I get:

```
`(dyn ActorFuture<Actor = MyWs, Output = ()> + 'static)` cannot be sent between threads safely
```

Can you give an advice how to listen for messages in service "A" and send data to my websocket "B"?

**Comment by fakeshadow** [comment]
From it's soruce code. This method would want a closure that can be send to a spawned thread.
And actix `Context` is not thread safe means they can not be sent there.
```rust
pub fn with_handler<F>(self, handler: F) -> Handler
    where
        F: Fn(Message) -> io::Result<()> + Send + 'static,
```

You can try to get an address of actor with `Context::address` and move the address to `with_handle` and use it sending message to MyWs with `Addr::do_send`. You would need a separate set of Message type and it's handler if it works.

**Comment by pashinin** [comment]
@fakeshadow Can you give an example?

**Comment by fakeshadow** [comment]
```rust
impl Actor for MyWs {
    type Context = ws::WebsocketContext<Self>;

    fn started(&mut self, ctx: &mut ws::WebsocketContext<Self>) {
        let addr = ctx.address();
        self.nats.subscribe(&format!("{}", self.uuid)).unwrap().with_handler(move |msg| {
            println!("Received {}", &msg);
            addr.do_send(Msg(msg));
            Ok(())
        });

struct Msg(<What ever the msg type handler gives>);
impl Message for Msg {
       type Result = ();
}

impl Handler<Msg> for MyWs {
    fn handle(&mut self, msg: server::Message, ctx: &mut Self::Context) {
        ctx.text(msg.0);
    }
}
```

The thing is actor can handle multiple types of messages. And the only thing that thread safe about an actor is it's address.

**Comment by pashinin** [comment]
Thank you!

I also found this (if it will help someone): https://stackoverflow.com/questions/58424473/how-to-send-server-events-using-rust-with-actix-web-and-websockets
