### ISSUE TITLE
websocket example client panics at unwrap

### ISSUE THREAD

**Issue by enedrio** [actix/examples#399]
The websocket example panics, because unwrap is being called on a None value in client.rs#L77.
https://github.com/actix/examples/blob/91865b3a2ad175166f472f8b3393eae1a1eb5996/websocket/src/client.rs#L77

After removing the first unwrap, the client starts alright.
But when typing a message the same error happens in client.rs#L91.
https://github.com/actix/examples/blob/91865b3a2ad175166f472f8b3393eae1a1eb5996/websocket/src/client.rs#L91

Removing both `unwrap()` solves the problem.

**Comment by aedeny** [comment]
Created PR #400

**Comment by JohnTitor** [comment]
#400 was merged already, closing.
