### ISSUE TITLE
track down broken links

### ISSUE THREAD

**Issue by robjtede** [actix/examples#413]
due to #411 there will be a bunch of broken links in READMEs now

**Comment by danitrod** [comment]
I'll try to hunt some down

**Comment by robjtede** [comment]
- https://github.com/actix/actix-web/blob/master/awc/README.md
- https://github.com/actix/actix-web/blob/master/actix-files/README.md
- https://github.com/actix/actix-extras/blob/master/actix-cors/README.md

**Comment by sahina** [comment]
i am working on this

**Comment by sahina** [comment]
opened PR https://github.com/actix/examples/pull/441
