### ISSUE TITLE
Why was Juniper 0.14.2 used instead of 0.15.x?

### ISSUE THREAD

**Issue by danielcasler** [actix/examples#417]
Could you tell me please why was Juniper 0.14.2 used instead of 0.15.x for the examples published 14 days ago?

**Comment by fakeshadow** [comment]
There is no man power dediceted to monitor every crate dep in examples repo and PRs are welcome for keeping examples updated.

**Comment by JohnTitor** [comment]
> published 14 days ago?

This is wrong, it's just not updated since #233.

**Comment by danielcasler** [comment]
> > published 14 days ago?
> 
> This is wrong, it's just not updated since #233.

My apologies, I thought it had been published 14-days ago. Not being updated in just over a year explains why 0.14.2 was used :)
