### ISSUE TITLE
Tera integration example doesn't work for actix-web 4.0 beta6

### ISSUE THREAD

**Issue by a3kov** [actix/examples#420]
In `not_found()` function:
```
error[E0308]: mismatched types
  --> src/templates.rs:28:27
   |
28 |         res.into_response(response.into_body()),
   |                           ^^^^^^^^^^^^^^^^^^^^ expected struct `actix_web::HttpResponse`, found struct `BaseHttpResponse`
   |
   = note: expected struct `actix_web::HttpResponse<B>`
              found struct `BaseHttpResponse<_>`
```

**Comment by fakeshadow** [comment]
Please use the example as is including it's dependencies in `Cargo.toml`.
actix-web v4 is still in beta and it contains break changes. actix/examples repo targets the latest stable version so it has to wait for future migration.

**Comment by a3kov** [comment]
I understand that it's not compatible (yet), the issue was about how to make it compatible :)

**Comment by fakeshadow** [comment]
It's not really an issue like I explained and that's the reason I closed it.

Please come by gitter/discord for some talk if you have problems on trying actix-web v4 beta. But in general we don't put to much effort in making a migration guide until it's stabled and when facing problems like not compatable your first choice is always use the stable version when you can.

**Comment by fakeshadow** [comment]
You can find the discord badge in actix-web repo's README session or use this directly https://discord.gg/NWpN5mmg3x

**Comment by a3kov** [comment]
Thank you, I actually already asked in the gitter channel.
