### ISSUE TITLE
[Question] Where can I find use cases for actix-web 4.x ?

### ISSUE THREAD

**Issue by nauu** [actix/examples#424]
After upgrading to 4.x, the original code has many errors，so where can I find use cases for actix-web 4.x ?

**Comment by JohnTitor** [comment]
I think API docs on docs.rs would be one of the good candidates. And the changelog (and the migration.md a bit) lists the breaking changes in v4, it should provide some help on migrating to v4. But note that v4 is still in beta, which means it isn't ready for general use. We'll update the examples here once having a stable release for it.
