### ISSUE TITLE
Simple file to db example

### ISSUE THREAD

**Issue by RazrFalcon** [actix/examples#43]
I'm looking for a simple example that shows how to upload a file to the server and put in in the db. Files are small. Usually less than 100KiB.

There is a `multipart` example, but it way too complex. I'm looking for something like:

```rust
fn add_file((file, state): (Binary, State<AppState>)) -> HttpResponse {
    // do stuff
}
```

Is it possible?

**Comment by fafhrd91** [comment]
This works

```rust
fn add_file(file: Bytes, state: State<AppState>) -> HttpResponse {
    // do stuff
}
```

**Comment by fafhrd91** [comment]
https://actix.rs/actix-web/actix_web/trait.FromRequest.html

**Comment by RazrFalcon** [comment]
I was so close...

Thanks a lot!
