### ISSUE TITLE
Websockets example outdated, not working with actix 0.12

### ISSUE THREAD

**Issue by joepio** [actix/examples#443]
The [websockets example](https://github.com/actix/examples/tree/master/websockets/websocket) doesn't work with `actix 0.12.0`.

I've tried using 0.12.0 with websockets, but failed to implement the Actor trait. Probably because I'm still kind of learning Actix, but having an up to date example might help to speed this process up.

**Comment by robjtede** [comment]
It's just not a compatible version (yet). you need to use actix 0.10/

**Comment by flip111** [comment]
@robjtede can you clarify, what needs to be compatible with what? I don't quite get your previous comment.

**Comment by robjtede** [comment]
This repo uses latest stable versions. If you check the cargo.toml for each example you'll find the compatible versions.

**Comment by flip111** [comment]
https://crates.io/crates/actix/versions  when doing a mouse over on `0.12.0` it says `(latest)`. joepio his request for an update to this version seems legit to me. Mind reopening the issue ?

**Comment by robjtede** [comment]
Sorry I means latest compatible versions. There's no point reopening this since nothing can be done about it. Actix 0.10 is the latest compatible version that works with actix-web-actors for websocket support.

**Comment by flip111** [comment]
Aaah that makes sense. Thanks.

**Comment by rokit** [comment]
> Actix 0.10 is the latest compatible version that works with actix-web-actors for websocket support

@robjtede I think that caveat belongs in the `readme`s of the websocket examples so that people stop trying to use > v0.10. I mean there were already two issues created for it. Hopefully it would save people some time.
