### ISSUE TITLE
Is there a way to load encrypted key with passphrase while building tls server?

### ISSUE THREAD

**Issue by powerory** [actix/examples#468]
Following loading code is in example for openssl(https://github.com/actix/examples/tree/master/security/openssl).
```
    // load ssl keys
    let mut builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
    builder
        .set_private_key_file("key.pem", SslFiletype::PEM)
        .unwrap();
    builder.set_certificate_chain_file("cert.pem").unwrap();

```
In this example, not encrypted key is used.
And If I use encrypted key by aes256 with passphrase, prompt requests entering passphrase in console like follows:

Enter PEM pass phrase:

This is might from openssl and I can skip this phase while decryption using openssl if I add `-passin pass:$passphrase`.
Is there such way (or api) to load private key with passphrase while building server?

**Comment by robjtede** [comment]
I'm not sure. Would advise you ask in the Rust community discord or, failing that, the rust-openssl repo discussions/issues.

**Comment by powerory** [comment]
Ok, I added an issue in rust-openssl repo. (https://github.com/sfackler/rust-openssl/issues/1585)

And if I get something from there or else, I will leave comment here.

**Comment by powerory** [comment]
https://github.com/sfackler/rust-openssl/issues/1585

It could be done by `private_key_from_pem_passphrase` and `set_private_key ` instead of `set_private_key_file`
And `read_to_end ` is also needed because `private_key_from_pem_passphrase `requires &[u8] as input parameter.
