### ISSUE TITLE
update to latest v4 rc in preparation for release

### ISSUE THREAD

**Issue by robjtede** [actix/examples#473]
There won't be any more significant changes from the latest beta so it's time to get a PR ready for this repo.

If someone takes this on, I will be able to mentor.

Finding the pain points will be helpful to getting the migration guide together.

**Comment by LukeMathWalker** [comment]
I can get started on this 😄

**Comment by LukeMathWalker** [comment]
[ ] basics/basics
[ ] basics/hello-world
[ ] basics/error-handling
[ ] basics/json-validation

**Comment by vardhanapoorv** [comment]
#514 for `security/web-cors` in above checklist.

**Comment by cgubbin** [comment]
#515 for `security/openssl`
#516 for `security/casbin`
#517 for `security/awc_https`

**Comment by robjtede** [comment]
thanks all for your help getting this repo migrated 🎉
