### ISSUE TITLE
Failed to connect to https host: received fatal alert: HandshakeFailure

### ISSUE THREAD

**Issue by huiali** [actix/examples#549]
Hello, clone the awc-https sample code to local and run, the following error occurs:

awc-https : [https://github.com/actix/examples/tree/master/https-tls/awc-https
](https://github.com/actix/examples/tree/master/https-tls/awc-https)

```MAP_URL = https://****/ping ```
```curl https://***/ping  --> pong!```

```
No cached session for DnsName(DnsName(DnsName("***.com")))
DEBUG rustls::client::hs] Not resuming any session
ERROR rustls::conn] TLS alert received: AlertMessagePayload {
        level: Fatal,
        description: HandshakeFailure,
    }
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Io(Custom { kind: InvalidData, error: AlertReceived(HandshakeFailure) }))', https-tls\awc-https\src\main.rs:14:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by robjtede** [comment]
Would you mind revealing what you're trying to connect to? If it's sensitive you can DM me on Discord.

**Comment by huiali** [comment]
> Would you mind revealing what you're trying to connect to? If it's sensitive you can DM me on Discord.

![image](https://user-images.githubusercontent.com/29728900/164966342-e6e1ba49-c974-42c5-9eaa-7144d362acab.png)

**Comment by huiali** [comment]
> Would you mind revealing what you're trying to connect to? If it's sensitive you can DM me on Discord.

https://cache1.t.nxin.com

[ INFO  awc_https] starting HTTP server at http://localhost:8080
[ INFO  actix_server::builder] Starting 2 workers
[ INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[ ERROR rustls::conn] TLS alert received: AlertMessagePayload {
        level: Fatal,
        description: HandshakeFailure,
    }
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Io(Custom { kind: InvalidData, error: AlertReceived(HandshakeFailure) }))', https-tls\awc-https\src\main.rs:14:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![image](https://user-images.githubusercontent.com/29728900/164967784-47ff9207-acbf-4a1b-a191-6875c9a15caf.png)


![image](https://user-images.githubusercontent.com/29728900/164967744-9d218126-a529-4697-b0b1-aebfd8a07b5b.png)

**Comment by huiali** [comment]
I can request correctly by using HTTP domain name.

https://cache1.t.nxin.com

[ INFO  actix_server::server] Actix runtime found; starting in Actix runtime
[ INFO  awc_https] it took 201ms to download image to memory
[ INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 5 "-" "
[ INFO  awc_https] it took 32ms to download image to memory
[ INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 5 "-" "
[ INFO  awc_https] it took 22ms to download image to memory
[ INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 5 "-" "

**Comment by huiali** [comment]
Hello, is there a solution?
