### ISSUE TITLE
websocket chat python file

### ISSUE THREAD

**Issue by Bechma** [actix/examples#551]
I'm learning about how to implement web sockets with actix and I was looking at the example linked from [here](https://actix.rs/docs/websockets/):

I understand the example, it's clear and I understand everything, but I don't get why is this python file there, I got 404 everytime that I run it :/
https://github.com/actix/examples/blob/master/websockets/chat/client.py

**Comment by JohnTitor** [comment]
Fixed by #575, thanks for reporting!
