### ISSUE TITLE
Reading POST data is slow (json example)

### ISSUE THREAD

**Issue by kodieg** [actix/examples#57]
I've started json example code and tried to send 1.8KB to all endpoints. Everytime request took over 1s (before actually failing due to bad json). I guess reading 1.8KB should take more than few milliseconds (over localhost). 

Steps to reproduce:
cd json; cargo run 
curl 'http://localhost:8080/extractor2' -X POST -d @req -H 'Content-Type: application/json'
where req is a file containing 1.8KB of data.

**Comment by fafhrd91** [comment]
should be fixed
