### ISSUE TITLE
JSON post examples sending to other actors

### ISSUE THREAD

**Issue by Firstyear** [actix/examples#61]
There are no example of using a JSON post where the request is sent to another actor, and the json deserialised correctly. The workflow in mind is:

```
index(request<AppState>) -> ... {
    req.payload()
        .from_err()
        .fold( ... bytes -> body)
        .and_then(body)  {
             let result_obj = serde_json::from_slice::<MyStruct>(&body);
             // send a custom error on Err(e) in result_obj
             // send the obj to another actor and then respond with json
             // IE request.state().actor.send().... 
        }
}
```

This is a reasonably complex example, incorporating many different components, and would be really important to have because there is no current example that demonstrates these components working together (json error handling and response, communicating to an actor, and handling the post). There are small elements of each through out the examples project, but without having a complete, tied together example it's really difficult to tie everything together.

**Comment by scull7** [comment]
It's not a JSON post example, but I have made an example to show how to send information between actors #64

**Comment by robjtede** [comment]
closing as stale; we're largely transitioning away from demonstrating actors in today's async landscape
