### ISSUE TITLE
Expand postgres example to include querying/fetching all

### ISSUE THREAD

**Issue by joeyfigaro** [actix/examples#628]
It looks like the postgres example shows how [inserting new rows](https://github.com/actix/examples/blob/master/databases/postgres/src/main.rs#L59-L81) works, but doesn't cover how you would implement row querying. 

The disel example shows inserts [and queries](https://github.com/actix/examples/blob/master/databases/diesel/src/actions.rs#L9-L21), however. 

Since [the sql is already available](https://github.com/actix/examples/blob/master/databases/postgres/sql/get_users.sql) for querying users, I imagine I can just implement a new handler using the example for inserts. 

If the changes are as straightforward as they appear, I should be able to have a PR done by end of day.

**Comment by joeyfigaro** [comment]
@robjtede day late, but PR is ready–thank you in advance. https://github.com/actix/examples/pull/629

**Comment by joeyfigaro** [comment]
Also @robjtede, thank you for all of your work on Actix. I just started learning Rust last week, and using actix to build out ideas has been a joy. Hopefully the changes in this PR will help other devs learning just like me. 

💪🏻

**Comment by robjtede** [comment]
Appreciate the support.

Contributions from newcomers are especially appreciated as I/we, being so deep in it, struggle to see things from your PoV. Thanks for the PR 🎉
