### ISSUE TITLE
Juniper implement Cors not working

### ISSUE THREAD

**Issue by Jayuda** [actix/examples#66]
Hello guys,
I used the example on the juniper folder, then added the cors. but the cors did not work.
Here's the extra I did:

```
    server::new(move || {
        App::with_state(AppState {
            executor: addr.clone(),
        })
            .middleware(middleware::Logger::default())
            .configure(|app| {
                Cors::for_app(app)
                    .allowed_origin("127.0.0.1:8000")
                    .allowed_methods(vec!["GET", "POST"])
                    .allowed_headers(vec![header::AUTHORIZATION, header::ACCEPT])
                    .allowed_header(header::CONTENT_TYPE)
                    .max_age(3600)
                    .resource("/graphql", |r| r.method(http::Method::POST).with(graphql))
                    .register()
            })
    }).bind("127.0.0.1:8000")
        .unwrap()
        .shutdown_timeout(2)
        .start();


```
if allowed_origin I replace with * it still does not work

log error :
```
 WARN 2018-12-07T08:53:57Z: actix_web::pipeline: Error occurred during request handling: Origin is not allowed to make this request
```

**Comment by DoumanAsh** [comment]
Are you sure your origin matches `127.0.0.1:800`?

To allow all origins, you don't need to use `allowed_origin` at all

**Comment by DoumanAsh** [comment]
If you want all access it, then please read carefully [allowed_origin](https://docs.rs/actix-web/0.7.15/actix_web/middleware/cors/struct.CorsBuilder.html#method.allowed_origin) docs

>Defaults to All.

You don't need to manually set wildcard like that, it is default behavior

When you set such origin, we actually try to match against `"*"`, not all origins

**Comment by Jayuda** [comment]
If I access from the client, for example upkes.com, an error like this appears
```
Access to fetch at 'http://127.0.0.1:8000/graphql' from origin 'https://upkes.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

log from actix show error : 
```
2018-12-08T03:09:12Z: actix_web::pipeline: Error occurred during request handling: One or more headers requested are not allowed
```

What should i set to allow upkes.com access to juniper. Thanks anyway.

**Comment by DoumanAsh** [comment]
Well, you need to configure right headers

**Comment by Jayuda** [comment]
Thanks a lot @DoumanAsh
