### ISSUE TITLE
simple-auth-server don't compile

### ISSUE THREAD

**Issue by fdb-hiroshima** [actix/examples#67]
Trying to compile simple-auth-server lead to this error : 
```
error[E0277]: the trait bound `uuid::Uuid: diesel::Expression` is not satisfied
  --> simple-auth-server/src/models.rs:39:52
   |
39 | #[derive(Debug, Serialize, Deserialize, Queryable, Insertable)]
   |                                                    ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `uuid::Uuid`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&'insert uuid::Uuid`
   = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Uuid>` for `&'insert uuid::Uuid`
```

**Comment by DoumanAsh** [comment]
@mygnu ping

**Comment by mygnu** [comment]
This is an issue with uuid and diesel compatibility. Please check you have only one version of Uuid crate in your lock file. and please don't upgrade this until Diesel has a support for it.
hope this helps

**Comment by fdb-hiroshima** [comment]
There are 3 versions of uuid in lock, 0.7.1 required by actix & reqwest , 0.5.1 by diesel, juniper & r2d2-example, and 0.6.5 for simple-auth-server.
Changing the version simple-auth-server require to the one of diesel seems to solve the issue

**Comment by mygnu** [comment]
@DoumanAsh @fdb-hiroshima  if you think it is resolved can you close this one
