### ISSUE TITLE
Is it possible to share app state between actors?

### ISSUE THREAD

**Issue by ivan-ochc** [actix/examples#74]
Is it possible to obtain **db_addr** inside **QueueActor** from `app_state`?  For example, I want to store message from the queue to the DB, therefore I have to get DB connection  inside QueueActor somehow. At the same time there should be simple REST API to GET data from the DB. Is it valid case in scope of actix, actix-web?

```
pub struct AppState {
    pub db_addr: Arc<Addr<DbActor>>,
    pub queue_addr: Arc<Addr<QueueActor>>
}
```

```
let server = server::new(|| {
     let db_addr = Arc::new(DbActor::start(host));
     let queue_addr = Arc::new(QueueActor::start(host));
     let app_state = AppState{db_addr, queue_addr};
     App::with_state(app_state)
            ...                              
});
```

**Comment by DoumanAsh** [comment]
Use `SystemRegistry` to store global actors and access them anywhere.

I'm not really sure what you want to achieve, but you cannot access `actix_web` from `Actor` so you need to store address inside your actor.

Please use gitter for such questions
