### ISSUE TITLE
 It is a bad idea to use .handler("/", ...)

### ISSUE THREAD

**Issue by CoderOffka** [actix/examples#76]
Everything that is written below is my **opinion**, **not an instruction**.

I think this is a bad idea. You can see similar code [here (static_index)](https://github.com/actix/examples/blob/master/static_index/src/main.rs#L18) and [here (simple-auth-server)](https://github.com/actix/examples/blob/master/simple-auth-server/src/app.rs#L49).

This is bad because you use it to access the "/static" folder or **to open the index.html file automatically**.
And if in the browser you open "/abc", then you will get the file "/abc/**index.html**" because you are not using the ".index_file()" method **correctly**

Bad idea:
```rust
.handler(
    "/",
    fs::StaticFiles::new("./static/").unwrap().index_file("index.html"))
```

Also, you **can't** use code like this:
```rust
.handler(
    "/",
    fs::StaticFiles::new("./static/").unwrap().index_file("index.html"))
.resource("/", |r| r.f(index))
```

You should use ".handler" only for specific folders. For ex.:
```rust
.handler(
    "/css",
    fs::StaticFiles::new("./static/css/").unwrap())
.handler(
    "/imgs",
    fs::StaticFiles::new("./imgs/").unwrap())
.handler(
    "/download",
    fs::StaticFiles::new("./download/").unwrap())
.handler(
    "/js",
    fs::StaticFiles::new("./static/js/").unwrap())
.resource("/", |r| r.f(index))
```
And if you want the "index.html" file to open automatically **on the main page** (and not in **every** folder), use code like this:
```rust
fn index(_: &HttpRequest) -> Result<fs::NamedFile> {
    Ok(fs::NamedFile::open("static/index.html")?)
}
...
.resource("/", |r| r.f(index))
```
P.S. @fafhrd91 я знаю, что Вы хороший программист и я слушал Ваше выступление про Rust и Python. Но мы не идеальны и мне кажется, что использовать index_file() вообще плохая идея. Возможно, это должно работать по другому, но у меня, например, это работает для каждой вложенной папки (или для каждого запроса в браузере), например "localhost/somefolder" вернет мне "localhost/somefolder/index.html", а точнее ошибку о том, что index.html не найден (особенно если прикрутить default_handler(p404)). Нужно сделать документацию для index_file или переписать этот метод. Или вообще выпилить его, т.к. он побуждает программистов писать ошибочный код, который работает не так, как они думали. Потому что везде в примерах index_file используется якобы для того, что бы его автоматически вызывать при запросе главной страницы сайта. Хотя по факту получается, что этот файл должен находиться в каждой вложенной папке, к которой применен .handler()

**Comment by DoumanAsh** [comment]
`index_file` is name of file, not full path in first place, it is done for cases when you want replacement to default file listing.

There is nothing wrong to show 404 on directory with no index, it is perfectly normal that you may not want to enable directory listing at all and only show own index for particular directories

P.s. use only english in issue tracker, github issues are public and not for personal messages(using native language)
