### ISSUE TITLE
Potential security Issue with the simple-auth-server

### ISSUE THREAD

**Issue by acycliczebra** [actix/examples#82]
Hi everyone,

I had a question about the following piece of code in the handlers of the simple-auth-server:

```rust
impl Handler<AuthData> for DbExecutor {
    type Result = Result<SlimUser, ServiceError>;
    fn handle(&mut self, msg: AuthData, _: &mut Self::Context) -> Self::Result {
        use schema::users::dsl::{users, email};
        let conn: &PgConnection = &self.0.get().unwrap();

        let mut items = users
            .filter(email.eq(&msg.email))
            .load::<User>(conn)?;

        if let Some(user) = items.pop() {
            match verify(&msg.password, &user.password) {
                Ok(matching) => if matching {
                        return Ok(user.into());
                },
                Err(_) => (),
            }
        }
        Err(ServiceError::BadRequest("Username and Password don't match".into()))
    }
}
```

My question is that when the database is filtering out the user names it will immediately return, but if it finds it and tries to verify with an incorrect password it will only return after a lengthy amount of time. Is this not prone to a timing attack? This can leak information about which users exist in the database and which don't by a malicious attacker.

Thanks

**Comment by DoumanAsh** [comment]
I'm a bit unsure how else you can verify without delay? If verification is security risk, then all authentication services that rely on combination of login and password are invalid?
Besides it is, as name implies, quite simple example of auth service.
It is not exactly supposed to be tuned for particular use case

cc @mygnu

**Comment by fafhrd91** [comment]
this problem is beyond example
