### ISSUE TITLE
Send JSON and file through Multipart, but got error

### ISSUE THREAD

**Issue by AspadaX** [actix/examples#860]
Here is how I wrote the request format. MpJson is the Json struct that I imported from actix-multipart. The request sent from Postman is shown as the following. 

```rust
fn default_maximum_text_split_size() -> u64 {
    return 256;
}

#[derive(Deserialize)]
pub struct CreateDocumentBySingleFileJsonRequest {
    #[serde(default = "default_maximum_text_split_size")]
    pub maximum_text_split_size: u64
}

// this is for handling using file upload to create documents
#[derive(MultipartForm)]
pub struct CreateDocumentBySingleFileRequest {
    #[multipart(limit = "2MB")]
    pub file: TempFile, 
    pub json: MpJson<CreateDocumentBySingleFileJsonRequest>
}
```
Request body and returned error in Postman
![image](https://github.com/user-attachments/assets/38cc36e0-1c52-4730-bf41-934d2ad66ffe)

Suppose that I need both json and the file sent from a multipart form, how should I send the body?

**Comment by AspadaX** [comment]
As I tested, the request is okay when sending from JavaScript and Python. It is not a big deal for actually using the library, just adds additional works when testing the api.

**Comment by andrew-caines** [comment]
i get the same error:
```rust
#[derive(Debug, Deserialize)]
pub struct Metadata {
    name: String,
}

#[derive(Debug, MultipartForm)]
pub struct UploadForm {
    #[multipart(limit = "10MB")]
    images: Vec<TempFile>,
    json: MPJson<Metadata>,
}
```
D:\DEV\work\impact-job-manager>curl -v --request POST --url http://localhost:3000/api/jobs/save_jobv2 -F json={"name":"named field"} -F file=@./Cargo.lock
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host localhost:3000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:3000...
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000
> POST /api/jobs/save_jobv2 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Length: 72244
> Content-Type: multipart/form-data; boundary=------------------------BbEjWPOA2dBT8LvThWU2p1
>
< HTTP/1.1 400 Bad Request
< content-length: 40
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< content-type: text/plain; charset=utf-8
< access-control-expose-headers: content-type
< access-control-allow-credentials: true
< date: Sat, 27 Jul 2024 20:50:04 GMT
<
* HTTP error before end of send, stop sending
* abort upload after having sent 65324 bytes
An error occurred processing field: json* Closing connection

I can not seem to get any JSON fields to properly be parsed? Is this me, or is there an issue?

**Comment by robjtede** [comment]
![2024-08-19_02 49 10-0f5a5fce](https://github.com/user-attachments/assets/90415961-74f1-4538-bf60-108b08dbac53)  
![2024-08-19_02 49 33-0a0868f6](https://github.com/user-attachments/assets/443dce3a-3865-4fd9-9510-332bec7fa2ad)


it looks like, in both the OP and further comments, the content-type field was missing
